"""

Revision ID: 33d32b5e9920
Revises: ff1ba02f1cf6
Create Date: 2026-03-19 19:11:32.796288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d32b5e9920'
down_revision = 'ff1ba02f1cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xw_Attendance',
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户ID'),
    sa.Column('event_date', sa.Date(), nullable=True, comment='活动日期'),
    sa.Column('start_time', sa.Time(), nullable=True, comment='到场时间'),
    sa.Column('end_time', sa.Time(), nullable=True, comment='离场时间'),
    sa.Column('effective_duration', sa.Integer(), nullable=True, comment='有效时长（单位：小时）'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xw_order',
    sa.Column('name', sa.String(length=64), nullable=True, comment='姓名'),
    sa.Column('student_no', sa.String(length=64), nullable=True, comment='学工号'),
    sa.Column('department', sa.String(length=64), nullable=True, comment='部门'),
    sa.Column('phone', sa.String(length=64), nullable=True, comment='联系电话'),
    sa.Column('computer', sa.String(length=64), nullable=True, comment='电脑型号'),
    sa.Column('issue', sa.String(length=255), nullable=True, comment='用户问题描述'),
    sa.Column('images', sa.String(length=255), nullable=True, comment='问题图片描述'),
    sa.Column('appointment_time', sa.DateTime(), nullable=True, comment='预约时间'),
    sa.Column('customer_notes', sa.String(length=255), nullable=True, comment='客户备注'),
    sa.Column('attend_time', sa.DateTime(), nullable=True, comment='到场时间'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='处理开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='处理结束时间'),
    sa.Column('status', sa.String(length=64), nullable=True, comment='状态（New,Ready,Running,Blocked,Terminated）'),
    sa.Column('result', sa.String(length=64), nullable=True, comment='结果（已解决，未解决）'),
    sa.Column('resolution_method', sa.String(length=255), nullable=True, comment='处理方式'),
    sa.Column('resolution_process', sa.String(length=255), nullable=True, comment='处理过程'),
    sa.Column('resolution_images', sa.String(length=255), nullable=True, comment='处理图片'),
    sa.Column('customer_feedback', sa.String(length=255), nullable=True, comment='客户反馈'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xw_order_user',
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户ID'),
    sa.Column('order_id', sa.BigInteger(), nullable=True, comment='工单ID'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xw_order_user')
    op.drop_table('xw_order')
    op.drop_table('xw_Attendance')
    # ### end Alembic commands ###
