"""create bbs

Revision ID: 5c9abfaff87b
Revises: dcc0a0be1d90
Create Date: 2026-01-29 16:07:41.042872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c9abfaff87b'
down_revision = 'dcc0a0be1d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snc_announcement',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snc_banner',
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('target_url', sa.String(length=255), nullable=True),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_permission',
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父id'),
    sa.Column('name', sa.String(length=64), nullable=True, comment='名称'),
    sa.Column('url', sa.String(length=255), nullable=True, comment='路径'),
    sa.Column('component', sa.String(length=64), nullable=True, comment='组件'),
    sa.Column('menu_type', sa.String(length=64), nullable=True, comment='菜单类型(0:一级菜单; 1:子菜单:2:按钮权限)'),
    sa.Column('perms', sa.String(length=255), nullable=True, comment='菜单权限编码'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_role',
    sa.Column('name', sa.String(length=64), nullable=True, comment='名称'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='描述'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_role_permission',
    sa.Column('role_id', sa.BigInteger(), nullable=True, comment='角色id'),
    sa.Column('permission_id', sa.BigInteger(), nullable=True, comment='权限id'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_user_role',
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户id'),
    sa.Column('role_id', sa.BigInteger(), nullable=True, comment='角色id'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('bbs_comment', 'id',
               existing_type=mysql.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.alter_column('bbs_post', 'id',
               existing_type=mysql.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.alter_column('bbs_thread', 'id',
               existing_type=mysql.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.alter_column('sys_user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               comment='邮箱',
               existing_nullable=True)
    op.alter_column('sys_user', 'phone',
               existing_type=mysql.VARCHAR(length=64),
               comment='电话',
               existing_nullable=True)
    op.alter_column('sys_user', 'username',
               existing_type=mysql.VARCHAR(length=64),
               comment='用户名',
               existing_nullable=True)
    op.alter_column('sys_user', 'nickname',
               existing_type=mysql.VARCHAR(length=64),
               comment='昵称',
               existing_nullable=True)
    op.alter_column('sys_user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               comment='密码',
               existing_nullable=True)
    op.alter_column('sys_user', 'salt',
               existing_type=mysql.VARCHAR(length=64),
               comment='盐',
               existing_nullable=True)
    op.alter_column('sys_user', 'avatar',
               existing_type=mysql.VARCHAR(length=255),
               comment='头像',
               existing_nullable=True)
    op.alter_column('sys_user', 'status',
               existing_type=mysql.VARCHAR(length=64),
               comment='状态',
               existing_nullable=True)
    op.alter_column('sys_user', 'id',
               existing_type=mysql.BIGINT(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_user', 'id',
               existing_type=mysql.BIGINT(),
               nullable=False,
               autoincrement=True)
    op.alter_column('sys_user', 'status',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='状态',
               existing_nullable=True)
    op.alter_column('sys_user', 'avatar',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='头像',
               existing_nullable=True)
    op.alter_column('sys_user', 'salt',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='盐',
               existing_nullable=True)
    op.alter_column('sys_user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='密码',
               existing_nullable=True)
    op.alter_column('sys_user', 'nickname',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='昵称',
               existing_nullable=True)
    op.alter_column('sys_user', 'username',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='用户名',
               existing_nullable=True)
    op.alter_column('sys_user', 'phone',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='电话',
               existing_nullable=True)
    op.alter_column('sys_user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='邮箱',
               existing_nullable=True)
    op.alter_column('bbs_thread', 'id',
               existing_type=mysql.BIGINT(),
               nullable=False,
               autoincrement=True)
    op.alter_column('bbs_post', 'id',
               existing_type=mysql.BIGINT(),
               nullable=False,
               autoincrement=True)
    op.alter_column('bbs_comment', 'id',
               existing_type=mysql.BIGINT(),
               nullable=False,
               autoincrement=True)
    op.drop_table('sys_user_role')
    op.drop_table('sys_role_permission')
    op.drop_table('sys_role')
    op.drop_table('sys_permission')
    op.drop_table('snc_banner')
    op.drop_table('snc_announcement')
    # ### end Alembic commands ###
