"""create bbs

Revision ID: f0d1eb6a8347
Revises: 4dd3ff620e43
Create Date: 2026-01-29 15:03:20.002238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0d1eb6a8347'
down_revision = '4dd3ff620e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('nickname', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('salt', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('avatar', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('del_flag', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
