"""init

Revision ID: ff1ba02f1cf6
Revises: 
Create Date: 2026-03-19 14:57:24.839043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff1ba02f1cf6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bbs_comment',
    sa.Column('post_id', sa.BigInteger(), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bbs_post',
    sa.Column('thread_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bbs_thread',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iv_attendance',
    sa.Column('attend_time', sa.DateTime(), nullable=True, comment='签到时间'),
    sa.Column('status', sa.String(length=64), nullable=True, comment='签到状态'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户ID'),
    sa.Column('interview_round_id', sa.BigInteger(), nullable=True, comment='面试轮次ID'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iv_comment',
    sa.Column('content', sa.String(length=255), nullable=True, comment='评价内容'),
    sa.Column('score', sa.Integer(), nullable=True, comment='评分'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户ID'),
    sa.Column('interview_round_id', sa.BigInteger(), nullable=True, comment='面试轮次ID'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iv_group',
    sa.Column('name', sa.String(length=64), nullable=True, comment='分组名称'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('interview_round_id', sa.BigInteger(), nullable=True, comment='面试轮次ID'),
    sa.Column('seat_number', sa.Integer(), nullable=True, comment='座位号'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iv_interview',
    sa.Column('name', sa.String(length=64), nullable=True, comment='面试名称'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iv_interview_round',
    sa.Column('name', sa.String(length=64), nullable=True, comment='轮次名称'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='用于区分一面二面'),
    sa.Column('department_id', sa.BigInteger(), nullable=True, comment='部门ID'),
    sa.Column('current_group_id', sa.BigInteger(), nullable=True, comment='当前分组ID'),
    sa.Column('interview_id', sa.BigInteger(), nullable=True, comment='面试ID'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iv_interview_user',
    sa.Column('interview_round_id', sa.BigInteger(), nullable=True, comment='面试轮次ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户ID'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iv_registration',
    sa.Column('name', sa.String(length=64), nullable=True, comment='姓名'),
    sa.Column('information', sa.Text(), nullable=True, comment='其他学生信息，JSON格式'),
    sa.Column('interview_id', sa.BigInteger(), nullable=True, comment='面试ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户ID'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snc_announcement',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snc_banner',
    sa.Column('name', sa.String(length=64), nullable=True, comment='名称'),
    sa.Column('image_url', sa.String(length=255), nullable=True, comment='图片链接'),
    sa.Column('target_url', sa.String(length=255), nullable=True, comment='跳转链接'),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('status', sa.String(length=64), nullable=True, comment='状态'),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_permission',
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父id'),
    sa.Column('name', sa.String(length=64), nullable=True, comment='名称'),
    sa.Column('url', sa.String(length=255), nullable=True, comment='路径'),
    sa.Column('component', sa.String(length=64), nullable=True, comment='组件'),
    sa.Column('menu_type', sa.String(length=64), nullable=True, comment='菜单类型(0:一级菜单; 1:子菜单:2:按钮权限)'),
    sa.Column('perms', sa.String(length=255), nullable=True, comment='菜单权限编码'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_role',
    sa.Column('name', sa.String(length=64), nullable=True, comment='名称'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='描述'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_role_permission',
    sa.Column('role_id', sa.BigInteger(), nullable=True, comment='角色id'),
    sa.Column('permission_id', sa.BigInteger(), nullable=True, comment='权限id'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_user',
    sa.Column('email', sa.String(length=255), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=64), nullable=True, comment='电话'),
    sa.Column('student_no', sa.String(length=64), nullable=True, comment='学工号'),
    sa.Column('username', sa.String(length=64), nullable=True, comment='用户名'),
    sa.Column('nickname', sa.String(length=64), nullable=True, comment='昵称'),
    sa.Column('password', sa.String(length=255), nullable=True, comment='密码'),
    sa.Column('salt', sa.String(length=64), nullable=True, comment='盐'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像'),
    sa.Column('status', sa.String(length=64), nullable=True, comment='状态'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_user_role',
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户id'),
    sa.Column('role_id', sa.BigInteger(), nullable=True, comment='角色id'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_user_role')
    op.drop_table('sys_user')
    op.drop_table('sys_role_permission')
    op.drop_table('sys_role')
    op.drop_table('sys_permission')
    op.drop_table('snc_banner')
    op.drop_table('snc_announcement')
    op.drop_table('iv_registration')
    op.drop_table('iv_interview_user')
    op.drop_table('iv_interview_round')
    op.drop_table('iv_interview')
    op.drop_table('iv_group')
    op.drop_table('iv_comment')
    op.drop_table('iv_attendance')
    op.drop_table('bbs_thread')
    op.drop_table('bbs_post')
    op.drop_table('bbs_comment')
    # ### end Alembic commands ###
